name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Usa múltiples instancias para distribuir las pruebas en paralelo
        spec: 
          - "cypress/integration/test1.spec.js"
          - "cypress/integration/test2.spec.js"
          - "cypress/integration/test3.spec.js"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress Tests
        run: |
          npx cypress run --spec ${{ matrix.spec }} --record --parallel --key ${{ secrets.CYPRESS_API_KEY }}
        env:
          CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}
