name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec: 
          # Aquí estamos creando grupos de pruebas diferentes
          - "cypress/e2e/scriptcypress/Flexitest/API/pruebaAPI.cy.js"
          - "cypress/e2e/scriptcypress/Flexitest/API/pruebaAPI.cy.js"
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Cypress Tests
        run: |
          npx cypress run --spec ${{ matrix.spec }} --record --parallel --key ${{ secrets.CYPRESS_API_KEY }}
        env:
          CYPRESS_API_KEY: ${{ secrets.CYPRESS_API_KEY }}
